export type Permission =
    | "product:read"
    | "product:create"
    | "product:update"
    | "product:delete"
    | "order:read"
    | "order:update"
    | "order:create"
    | "order:cancel"
    | "coupon:create"
    | "coupon:update"
    | "coupon:delete"
    | "user:read"
    | "user:update"
    | "report:read"
    | "admin:manage"
    | "superadmin:manage"